// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyvhTZUnBSrsZVWedbcMYTzz86TJXWefo',
    appId: '1:734314445614:web:9a327da7ef3f7f5d2b98bf',
    messagingSenderId: '734314445614',
    projectId: 'group2-campus-system',
    authDomain: 'group2-campus-system.firebaseapp.com',
    storageBucket: 'group2-campus-system.firebasestorage.app',
    measurementId: 'G-BJ11R57M97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIP9DdoGxzcZYLBGsJjhL22ECxRVhMYuY',
    appId: '1:734314445614:android:203ca8fc2c2fc7d92b98bf',
    messagingSenderId: '734314445614',
    projectId: 'group2-campus-system',
    storageBucket: 'group2-campus-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi1JCpuhN8hpOENNMX0U_W01Aqiy0oYkQ',
    appId: '1:734314445614:ios:98b710a398513bab2b98bf',
    messagingSenderId: '734314445614',
    projectId: 'group2-campus-system',
    storageBucket: 'group2-campus-system.firebasestorage.app',
    iosBundleId: 'com.example.group2CampusSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi1JCpuhN8hpOENNMX0U_W01Aqiy0oYkQ',
    appId: '1:734314445614:ios:98b710a398513bab2b98bf',
    messagingSenderId: '734314445614',
    projectId: 'group2-campus-system',
    storageBucket: 'group2-campus-system.firebasestorage.app',
    iosBundleId: 'com.example.group2CampusSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyvhTZUnBSrsZVWedbcMYTzz86TJXWefo',
    appId: '1:734314445614:web:7aa22ce4298788852b98bf',
    messagingSenderId: '734314445614',
    projectId: 'group2-campus-system',
    authDomain: 'group2-campus-system.firebaseapp.com',
    storageBucket: 'group2-campus-system.firebasestorage.app',
    measurementId: 'G-RM7MXR3QRB',
  );
}
